# These are supported funding model platforms

github: [Daveiano] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom:
  ["https://paypal.me/davidbaetge", "https://www.buymeacoffee.com/daveiano"]
