#encoding UTF-8

<script
  type="module"
  src="https://1.www.s81c.com/common/carbon/web-components/version/v1.21.0/data-table.min.js"
></script>
<script
  type="module"
  src="https://1.www.s81c.com/common/carbon/web-components/version/v1.21.0/pagination.rtl.min.js"
></script>

<div class="bx--col">
  <div class="bx--tile data-table-tile">
    <div class="bx--row">
      <header class="bx--col section-header">
        <h2>Schöne Tabelle</h2>
      </header>
    </div>
    <div class="bx--row">
      <div class="bx--col"></div>
    </div>
  </div>
</div>
