name: Tests

on:
  push:
    branches: [1.x, 2.x, 2.*.x, 3.x]
    paths:
      - "**.py"
      - skins/**
      - bin/**
      - test/**
      - package.json
      - yarn.lock
      - playwright.config.ts
  pull_request:
    branches: [1.x, 2.x, 2.*.x, 3.x]
    paths:
      - "**.py"
      - skins/**
      - bin/**
      - test/**
      - package.json
      - yarn.lock
      - playwright.config.ts

jobs:
  shunit2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"

      - name: Install yarn and dependecies
        run: yarn install

      - name: Set custom run basePath
        run: |
          echo ${GITHUB_WORKSPACE}/test/e2e-tests/artifacts-custom-weewx-html/public_html/ \
          sed -i -z -e "s|base_path = \/home\/dba\/dev\/weewx-wdc\/test\/e2e-tests\/artifacts-custom-weewx-html\/public_html/|base_path = ${GITHUB_WORKSPACE}\/test\/e2e-tests\/artifacts-custom-weewx-html\/public_html\/|g" test/test_install_report/src/skin-custom.conf \
          echo $(cat test/test_install_report/src/skin-custom.conf)

      - name: Run shunit2 tests
        run: ./test/run_tests.sh

      - name: Upload log artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test_install_report_artifacts
          path: test/test_install_report/artifacts/

      - name: Upload alternative html
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-alternative-weewx-html
          path: test/test_install_report/artifacts-alternative-weewx-html/

      - name: Upload classic html
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-classic-weewx-html
          path: test/test_install_report/artifacts-classic-weewx-html/

      - name: Upload custom html
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-custom-weewx-html
          path: test/test_install_report/artifacts-custom-weewx-html/

      - name: Upload weewx-DWD html
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-dwd-weewx-html
          path: test/test_install_report/artifacts-dwd-weewx-html/

  playwright:
    needs: shunit2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 🔨 Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"

      - name: 🔨 install yarn and dependecies
        run: yarn install

      - name: install playwright deps
        run: yarn playwright install --with-deps

      - name: Download alternative html
        uses: actions/download-artifact@v3
        with:
          name: artifacts-alternative-weewx-html
          path: test/e2e-tests/artifacts-alternative-weewx-html

      - name: Download classic html
        uses: actions/download-artifact@v3
        with:
          name: artifacts-classic-weewx-html
          path: test/e2e-tests/artifacts-classic-weewx-html

      - name: Download custom html
        uses: actions/download-artifact@v3
        with:
          name: artifacts-custom-weewx-html
          path: test/e2e-tests/artifacts-custom-weewx-html

      - name: Download weewx-dwd html
        uses: actions/download-artifact@v3
        with:
          name: artifacts-dwd-weewx-html
          path: test/e2e-tests/artifacts-dwd-weewx-html

      - name: Run playwright tests
        run: yarn run test:e2e

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: test/e2e-tests/playwright-report
