name: Tests

on:
  push:
    branches: [1.x, 2.x]
    paths:
      - "**.py"
      - skins/**
      - bin/**
      - test/**
      - package.json
  pull_request:
    branches: [1.x, 2.x]
    paths:
      - "**.py"
      - skins/**
      - bin/**
      - test/**
      - package.json

jobs:
  shunit2-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 🔨 Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"

      - name: 🔨 install yarn and dependecies
        run: yarn install

      - name: Run shunit2 tests
        run: ./test/run_tests.sh

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test_install_report_artifacts
          path: test/test_install_report/artifacts/

      - name: 🔨 uninstall Yarn
        if: always()
        run: npm uninstall -g yarn
